# vars :: {"9009": "server.port"}
uwsgi:
  http: :9009
  wsgi-file: src/core/server.py
  # for :: {% for item in all_models %} :: {"sample-module":"item.module.name.kebab_case", "example-item": "item.model.name.kebab_case"}
  route: ^/sample-module/example-item/create static:../html/srv/sample-module/example-item/index.html
  route: ^/sample-module/example-item/index(.*) static:../html/srv/sample-module/example-item/index$1
  load-file-in-cache: ../html/srv/sample-module/example-item/index.html
  route: ^/sample-module/example-item/(.*) static:../html/srv/sample-module/example-item/instance.html
  load-file-in-cache: ../html/srv/sample-module/example-item/instance.html
  # end for ::
  static-map: /=../html/srv/
  static-index: index.html
  static-expires: /* 0
  
  py-auto-reload: 1
