# vars :: {"5005": "server.port"}
uwsgi:
  http: :5005
  wsgi-file: src/core/server.py
  # for :: {% for item in all_models %} :: {"test-module":"item.module.name.kebab_case", "single-model": "item.model.name.kebab_case", "single model": "item.model.name.lower_case"}

  # single model
  route: ^/test-module/single-model/create static:../html/srv/test-module/single-model/index.html
  route: ^/test-module/single-model/index(.*) static:../html/srv/test-module/single-model/index$1
  load-file-in-cache: ../html/srv/test-module/single-model/index.html
  route: ^/test-module/single-model/(.*) static:../html/srv/test-module/single-model/instance.html
  load-file-in-cache: ../html/srv/test-module/single-model/instance.html

  # end for ::

  # ignore ::
  # multi model
  route: ^/test-module/multi-model/create static:../html/srv/test-module/multi-model/index.html
  route: ^/test-module/multi-model/index(.*) static:../html/srv/test-module/multi-model/index$1
  load-file-in-cache: ../html/srv/test-module/multi-model/index.html
  route: ^/test-module/multi-model/(.*) static:../html/srv/test-module/multi-model/instance.html
  load-file-in-cache: ../html/srv/test-module/multi-model/instance.html
  # end ignore ::

  static-map: /=../html/srv/
  static-index: index.html
  static-expires: /* 0
  
  py-auto-reload: 1